### ISSUE TITLE
NestedArray test is failing

### ISSUE THREAD

**Issue by nekronos** [fusetools/fuselibs-public#1006]
This test is crashing https://github.com/fusetools/fuselibs-public/blob/master/Source/Fuse.Models/Tests/Model.Test.uno#L15

**Comment by kusma** [comment]
```
System.Exception: Incomplete or duplicate unrooting: Fuse.Reactive.Each/
   at Fuse.Node.UnrootInternal() in C:\BuildAgent-1\work\452c9bcd4266d21e\Source\build\Fuse.Nodes\1.6.0\Node.Rooting.uno:line 156
   at Fuse.Node.Unrelate(Visual parent, Node child) in C:\BuildAgent-1\work\452c9bcd4266d21e\Source\build\Fuse.Nodes\1.6.0\Node.Rooting.uno:line 192
   at Fuse.Visual.OnRemoved(Node b) in C:\BuildAgent-1\work\452c9bcd4266d21e\Source\build\Fuse.Nodes\1.6.0\Visual.Children.uno:line 149
   at Fuse.Visual.Remove(Node item) in C:\BuildAgent-1\work\452c9bcd4266d21e\Source\build\Fuse.Nodes\1.6.0\Visual.Children.uno:line 189
   at Fuse.Visual.BeginRemoveChild(Node n, Action`1 then) in C:\BuildAgent-1\work\452c9bcd4266d21e\Source\build\Fuse.Nodes\1.6.0\Visual.BeginRemove.uno:line 102
   at Fuse.Reactive.Instantiator.RemoveFromParent(Node n) in C:\BuildAgent-1\work\452c9bcd4266d21e\Source\build\Fuse.Reactive.Bindings\1.6.0\Instantiator.uno:line 166
   at Fuse.Reactive.Instantiator.CleanupWindowItem(WindowItem wi) in C:\BuildAgent-1\work\452c9bcd4266d21e\Source\build\Fuse.Reactive.Bindings\1.6.0\Instantiator.uno:line 763
   at Fuse.Reactive.Instantiator.DisposeWindowItem(WindowItem wi) in C:\BuildAgent-1\work\452c9bcd4266d21e\Source\build\Fuse.Reactive.Bindings\1.6.0\Instantiator.uno:line 756
   at Fuse.Reactive.Instantiator.RemoveAvailableItems() in C:\BuildAgent-1\work\452c9bcd4266d21e\Source\build\Fuse.Reactive.Bindings\1.6.0\Instantiator.uno:line 738
   at Fuse.Reactive.Instantiator.OnUnrooted() in C:\BuildAgent-1\work\452c9bcd4266d21e\Source\build\Fuse.Reactive.Bindings\1.6.0\Instantiator.uno:line 139
   at Fuse.Node.UnrootInternal() in C:\BuildAgent-1\work\452c9bcd4266d21e\Source\build\Fuse.Nodes\1.6.0\Node.Rooting.uno:line 161
   at Fuse.Visual.OnUnrooted() in C:\BuildAgent-1\work\452c9bcd4266d21e\Source\build\Fuse.Nodes\1.6.0\Visual.uno:line 155
   at Fuse.Elements.Element.OnUnrooted() in C:\BuildAgent-1\work\452c9bcd4266d21e\Source\build\Fuse.Elements\1.6.0\Element.Node.uno:line 50
   at Fuse.Controls.Control.OnUnrooted() in C:\BuildAgent-1\work\452c9bcd4266d21e\Source\build\Fuse.Controls\1.6.0\Control.Background.uno:line 91
   at Fuse.Controls.LayoutControl.OnUnrooted() in C:\BuildAgent-1\work\452c9bcd4266d21e\Source\build\Fuse.Controls.Panels\1.6.0\LayoutControl.uno:line 126
   at Fuse.Controls.Panel.OnUnrooted() in C:\BuildAgent-1\work\452c9bcd4266d21e\Source\build\Fuse.Controls.Panels\1.6.0\Panel.uno:line 79
   at Fuse.Node.UnrootInternal() in C:\BuildAgent-1\work\452c9bcd4266d21e\Source\build\Fuse.Nodes\1.6.0\Node.Rooting.uno:line 161
   at Fuse.Visual.OnUnrooted() in C:\BuildAgent-1\work\452c9bcd4266d21e\Source\build\Fuse.Nodes\1.6.0\Visual.uno:line 155
   at Fuse.Elements.Element.OnUnrooted() in C:\BuildAgent-1\work\452c9bcd4266d21e\Source\build\Fuse.Elements\1.6.0\Element.Node.uno:line 50
   at Fuse.Controls.Control.OnUnrooted() in C:\BuildAgent-1\work\452c9bcd4266d21e\Source\build\Fuse.Controls\1.6.0\Control.Background.uno:line 91
   at Fuse.Controls.LayoutControl.OnUnrooted() in C:\BuildAgent-1\work\452c9bcd4266d21e\Source\build\Fuse.Controls.Panels\1.6.0\LayoutControl.uno:line 126
   at Fuse.Controls.Panel.OnUnrooted() in C:\BuildAgent-1\work\452c9bcd4266d21e\Source\build\Fuse.Controls.Panels\1.6.0\Panel.uno:line 79
   at Fuse.Node.UnrootInternal() in C:\BuildAgent-1\work\452c9bcd4266d21e\Source\build\Fuse.Nodes\1.6.0\Node.Rooting.uno:line 161
   at Fuse.Node.Unrelate(Visual parent, Node child) in C:\BuildAgent-1\work\452c9bcd4266d21e\Source\build\Fuse.Nodes\1.6.0\Node.Rooting.uno:line 192
   at Fuse.Visual.OnRemoved(Node b) in C:\BuildAgent-1\work\452c9bcd4266d21e\Source\build\Fuse.Nodes\1.6.0\Visual.Children.uno:line 149
   at Fuse.Visual.Uno.Collections.ICollection<Fuse.Node>.Clear() in C:\BuildAgent-1\work\452c9bcd4266d21e\Source\build\Fuse.Nodes\1.6.0\Visual.Children.uno:line 172
   at Fuse.RootViewport.Uno.IDisposable.Dispose() in C:\BuildAgent-1\work\452c9bcd4266d21e\Source\build\Fuse.Nodes\1.6.0\RootViewport.uno:line 95
   at FuseTest.TestRootPanel.Uno.IDisposable.Dispose() in C:\BuildAgent-1\work\452c9bcd4266d21e\Source\Fuse.Common\Tests\FuseTest\TestRootNode.uno:line 60
   at Fuse.Models.Test.ModelTest.NestedArray() in C:\BuildAgent-1\work\452c9bcd4266d21e\Source\Fuse.Models\Tests\Model.Test.uno:line 18
   at MainClass.Invoke___Fuse_Models_Test_ModelTest_NestedArray()
   at Uno.Testing.AbstractRunner.RunTest(NamedTestMethod test) in C:\BuildAgent-1\work\452c9bcd4266d21e\Stuff\lib\Uno.Testing\1.6.0\AbstractRunner.uno:line 109
```
