### ISSUE TITLE
App crash when pressing back-button twice

### ISSUE THREAD

**Issue by trusis666** [fusetools/fuselibs-public#1066]
Reported on a [forums](https://www.fusetools.com/community/forums/bug_reports/app_crash_when_pressing_back-button_twice).

Fuse 1.7

The App is crashing when pressing the back button (or back in preview mode on PC) twice when there is nothing to go back to. First time nothing happens, second press the App crashes with stacktrace:
```
[Viewport]: System.NullReferenceException: Object reference not set to an instance of an object.
   at Fuse.Navigation.Router.GoUp() in C:\Users\nicolai\AppData\Local\Fusetools\Packages\Fuse.Navigation\1.7.2\Router.uno:line 278
   at Fuse.Navigation.Router.GoBack() in C:\Users\nicolai\AppData\Local\Fusetools\Packages\Fuse.Navigation\1.7.2\Router.uno:line 263
   at Fuse.Navigation.Router.OnKeyPressed(Object sender, KeyEventArgs args) in C:\Users\nicolai\AppData\Local\Fusetools\Packages\Fuse.Navigation\1.7.2\Router.uno:line 157
   at Fuse.Input.KeyPressed.Invoke(KeyPressedHandler handler, Object sender, KeyPressedArgs args) in C:\Users\nicolai\AppData\Local\Fusetools\Packages\Fuse.Nodes\1.7.2\Input\Keyboard.uno:line 63
   at Fuse.VisualEvent`2.InvokeInternal(THandler handler, Object sender, TArgs args) in C:\Users\nicolai\AppData\Local\Fusetools\Packages\Fuse.Nodes\1.7.2\Event.uno:line 149
```
This is on Fuse 1.7. In 1.6 the exact same code works without a crash. Code example of minimum App that recreates the crash:
```
<App>
	<Router ux:Name="router"/>

	<ClientPanel>
		<Navigator DefaultPath="home">
			<Page ux:Template="home">
				<PageControl ux:Name="containerControl">
					<Page>
						<Text Value="Page 1" />
					</Page>
				</PageControl>	
			</Page>
		</Navigator>
	</ClientPanel>
</App>
```

**Comment by HirenBharodiya** [comment]
This issue is still exist in Fuse 1.7.1

**Comment by trusis666** [comment]
The issue still exists in Fuse 1.7.3, but only on Android 6.0 device.
Got this error:
`Uno.NullReferenceException: Object reference was null`
