### ISSUE TITLE
ImageTest.RetryReload failure

### ISSUE THREAD

**Issue by kusma** [fusetools/fuselibs-public#125]
ImageTest.RetryReload in the Fuse.Controls.Primitives-tests fails consistently for me when I *only* run that test-project. If I run all tests, it passes just fine...

> $ Stuff/uno test -tdotnet Source/Fuse.Controls.Primitives/Tests/
> Searching for tests in:
>  Source/Fuse.Controls.Primitives/Tests/
> Starting project 'Fuse.Controls.Primitives.Test', target 'DotNet'
> Started test runner on http://localhost:15566/
> Configuring (0.4 s)
> Compiling syntax tree (1.7 s)
> Generating code and data (4.4 s)
> 
> Build completed in 6.51 seconds
> 
> ---
> GL_VERSION: 4.5.0 NVIDIA 382.05
> GL_VENDOR: NVIDIA Corporation
> GL_RENDERER: GeForce GTX 770/PCIe/SSE2
> OK:      Fuse.Controls.Primitives.Test.Fuse.Controls.Primitives.Test.CurveTest.Close (64,457 µs)
> OK:      Fuse.Controls.Primitives.Test.Fuse.Controls.Primitives.Test.CurveTest.MinPoints (165,120 µs)
> OK:      Fuse.Controls.Primitives.Test.Fuse.Controls.Primitives.Test.ImageTest.Fail (30,137 µs)
> OK:      Fuse.Controls.Primitives.Test.Fuse.Controls.Primitives.Test.ImageTest.NullSource (2,771 µs)
> FAILED:  Fuse.Controls.Primitives.Test.Fuse.Controls.Primitives.Test.ImageTest.RetryReload
>          Exception was thrown: System.Exception: Unchecked, queued Diagnostics!
>    at FuseTest.RecordDiagnosticGuard.Dispose() in C:\Users\erik\src\fuselibs\Source\Fuse.Common\Tests\FuseTest\TestBase.uno:line 65
>    at Fuse.Controls.Primitives.Test.ImageTest.RetryReload() in C:\Users\erik\src\fuselibs\Source\Fuse.Controls.Primitives\Tests\Image.Test.uno:line 55
>    at MainClass.Invoke___Fuse_Controls_Primitives_Test_ImageTest_RetryReload()
>    at Uno.Testing.AbstractRunner.RunTest(NamedTestMethod test) in C:\Users\erik\AppData\Local\Fusetools\Packages\Uno.Testing\1.0.12\$.uno:line 92
> OK:      Fuse.Controls.Primitives.Test.Fuse.Controls.Primitives.Test.ShadowTest.ColorPanel (64,845 µs)
> OK:      Fuse.Controls.Primitives.Test.Fuse.Controls.Primitives.Test.ShadowTest.ColorRectangle (8,228 µs)
> OK:      Fuse.Controls.Primitives.Test.Fuse.Controls.Primitives.Test.ShadowTest.CornerRadius (2,547 µs)
> OK:      Fuse.Controls.Primitives.Test.Fuse.Controls.Primitives.Test.ShadowTest.Falloff (1,818 µs)
> OK:      Fuse.Controls.Primitives.Test.Fuse.Controls.Primitives.Test.ShadowTest.InvisiblePanel (1,439 µs)
> OK:      Fuse.Controls.Primitives.Test.Fuse.Controls.Primitives.Test.ShadowTest.InvisibleRectangle (1,458 µs)
> OK:      Fuse.Controls.Primitives.Test.Fuse.Controls.Primitives.Test.ShadowTest.Padding (2,108 µs)
> OK:      Fuse.Controls.Primitives.Test.Fuse.Controls.Primitives.Test.ShadowTest.Underlay (1,473 µs)
> OK:      Fuse.Controls.Primitives.Test.Fuse.Controls.Primitives.Test.ShapeTest.LoadingImageFill (11,011 µs)
> OK:      Fuse.Controls.Primitives.Test.Fuse.Controls.Primitives.Test.ShapeTest.LoadingResource (1,546 µs)
> OK:      Fuse.Controls.Primitives.Test.Fuse.Controls.Primitives.Test.ShapeTest.NullFill (272 µs)
> OK:      Fuse.Controls.Primitives.Test.Fuse.Controls.Primitives.Test.ShapeTest.NullStoke (578 µs)
> OK:      Fuse.Controls.Primitives.Test.Fuse.Controls.Primitives.Test.TextControlTest.MaxValueCrashBug (5,531 µs)
> OK:      Fuse.Controls.Primitives.Test.Fuse.Controls.Primitives.Test.TextControlTest.TextInputBinding (47,998 µs)
> OK:      Fuse.Controls.Primitives.Test.Fuse.Controls.Primitives.Test.TextTests.FontSizeAffectsHeight (4,399 µs)
> OK:      Fuse.Controls.Primitives.Test.Fuse.Controls.Primitives.Test.TextTests.LineSpacingAffectsHeight (3,139 µs)
> OK:      Fuse.Controls.Primitives.Test.Fuse.Controls.Primitives.Test.TextTests.TextTruncationAffectsRenderBounds (26,905 µs)
> OK:      Fuse.Controls.Primitives.Test.Fuse.Controls.Primitives.Test.TextTests.TextWrappingAffectsSize (2,532 µs)
> OK:      Fuse.Controls.Primitives.Test.Fuse.Gestures.Test.RangeControlTests.Orientation (20,524 µs)
> OK:      Fuse.Controls.Primitives.Test.FuseTest.SatisfyUnoTest.Test (295 µs)
> 
> Built & ran 25 tests in 10.48 seconds (471,131 µs)
> Failures: 1

**Comment by kusma** [comment]
Actually, seems this was a PEBCAC, where I used the wrong uno-version.
