### ISSUE TITLE
BusyTest.CompletedReset and BusyTest.JavaScript spurious failure

### ISSUE THREAD

**Issue by kusma** [fusetools/fuselibs-public#145]
> FAILED:  Fuse.Triggers.Test.Fuse.Triggers.Test.BusyTest.CompletedReset
>          Assertion failed in 'CompletedReset', at C:\projects\fuselibs-public\Source\Fuse.Triggers\Tests\Busy.Test.uno:337
>            Expected: 2
>            But got : 1
> OK:      Fuse.Triggers.Test.Fuse.Triggers.Test.BusyTest.IsHandled (1,621 �s)
> FAILED:  Fuse.Triggers.Test.Fuse.Triggers.Test.BusyTest.JavaScript
>          Exception was thrown: System.Exception: Unchecked, queued Diagnostics!
>    at FuseTest.RecordDiagnosticGuard.Dispose() in C:\projects\fuselibs-public\Source\Fuse.Common\Tests\FuseTest\TestBase.uno:line 65
>    at Fuse.Triggers.Test.BusyTest.JavaScript() in C:\projects\fuselibs-public\Source\Fuse.Triggers\Tests\Busy.Test.uno:line 99
>    at MainClass.Invoke___Fuse_Triggers_Test_BusyTest_JavaScript()
>    at Uno.Testing.AbstractRunner.RunTest(NamedTestMethod test) in C:\projects\fuselibs-public\Stuff\lib\Uno.Testing\1.1.0\$.uno:line 110

See [this log](https://ci.appveyor.com/project/fusetools/fuselibs-public/build/351)

**Comment by kusma** [comment]
I don't think I've seen this in a while...
