### ISSUE TITLE
Crashing app in the last commit (47e524a)

### ISSUE THREAD

**Issue by ckarmy** [fusetools/fuselibs-public#262]
In the last commit **(47e524a)** my app crash when I export to a device (Android and IOS). Work fine on the preview and in the stable version.
Sorry for don't be specific but I get this log when I export the app:

```
fuse build --target=Android --run
Uno 1.1.3 (build 5510) macOS 10.12 i386 933ea5b

Configuring (6.2 s)
Installing dependencies (0.4 s)
Compiling syntax tree (2.6 s)
Generating code and data (10.9 s)
Building Android app
2/2: Ptei.apk
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
(3:31)

Build completed in 231.37 seconds

---
Installing APK on 1 device(s)
Launching activity 'tei'
Running logcat on 'e21b5b8a'
E/Zygote  (  417): MountEmulatedStorage()
E/Zygote  (  417): v2
I/libpersona(  417): KNOX_SDCARD checking this for 10222
I/libpersona(  417): KNOX_SDCARD not a persona
I/SELinux (  417): Function: selinux_compare_spd_ram, SPD-policy is existed. and_ver=SEPF_GT-I9505_5.0.1-1 ver=51
I/SELinux (  417): Function: selinux_compare_spd_ram , priority [1] , priority version is VE=SEPF_GT-I9505_5.0.1-1_0051
E/SELinux (  417): [DEBUG] get_category: variable seinfo: default sensitivity: NULL, cateogry: NULL
I/ActivityManager(  905): Start proc com.tei for activity com.tei/.tei: pid=417 uid=10222 gids={50222, 9997, 1028, 1015, 3003} abi=armeabi-v7a
I/art     (  417): Late-enabling -Xcheck:jni
D/ResourcesManager(  417): creating new AssetManager and set to /data/app/com.tei-1/base.apk
D/tei (  417): SDK: 21
I/Adreno-EGL(  417): <qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build:  ()
I/Adreno-EGL(  417): OpenGL ES Shader Compiler Version: E031.25.03.06
I/Adreno-EGL(  417): Build Date: 01/24/15 Sat
I/Adreno-EGL(  417): Local Branch: AF11_RB1_AU15
I/Adreno-EGL(  417): Remote Branch: 
I/Adreno-EGL(  417): Local Patches: 
I/Adreno-EGL(  417): Reconstruct Branch: 
W/InstanceID/Rpc(  417): Found 10036
I/WebViewFactory(  417): Loading com.google.android.webview version 59.0.3071.125 (code 307112500)
D/ResourcesManager(  417): creating new AssetManager and set to /data/app/com.google.android.webview-1/base.apk
I/art     (  417): Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.TokenBindingManagerAdapter>
I/art     (  417): Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.TokenBindingManagerAdapter>
I/art     (  417): Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.ServiceWorkerControllerAdapter>
I/art     (  417): Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.ServiceWorkerControllerAdapter>
I/cr_LibraryLoader(  417): Time to load native libraries: 2 ms (timestamps 3196-3198)
I/chromium(  417): [INFO:library_loader_hooks.cc(144)] Chromium logging enabled: level = 0, default verbosity = 0
I/cr_LibraryLoader(  417): Expected native library version number "59.0.3071.125", actual native library version number "59.0.3071.125"
I/cr_BrowserStartup(  417): Initializing chromium process, singleProcess=true
I/art     (  417): Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.WebViewContentsClientAdapter$WebResourceErrorImpl>
I/art     (  417): Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.WebViewContentsClientAdapter$WebResourceErrorImpl>
W/cr_BindingManager(  417): Cannot setInForeground() - never saw a connection for the pid: 417
D/ConnectivityManager.CallbackHandler(  417): CM callback handler got msg 524290
I/art     (  417): Rejecting re-init on previously-failed class java.lang.Class<org.chromium.content.browser.FloatingActionModeCallback>
I/art     (  417): Rejecting re-init on previously-failed class java.lang.Class<org.chromium.content.browser.FloatingActionModeCallback>
W/cr_media(  417): Requires BLUETOOTH permission
E/libEGL  (  417): validate_display:255 error 3008 (EGL_BAD_DISPLAY)
W/AudioCapabilities(  417): Unsupported mime audio/mpeg-L1
W/AudioCapabilities(  417): Unsupported mime audio/mpeg-L2
W/AudioCapabilities(  417): Unsupported mime audio/x-ms-wma
W/AudioCapabilities(  417): Unsupported mime audio/x-ima
W/AudioCapabilities(  417): Unsupported mime audio/qcelp
W/AudioCapabilities(  417): Unsupported mime audio/evrc
W/VideoCapabilities(  417): Unsupported mime video/wvc1
W/VideoCapabilities(  417): Unsupported mime video/x-ms-wmv
W/VideoCapabilities(  417): Unrecognized profile/level 32768/2 for video/mp4v-es
W/VideoCapabilities(  417): Unsupported mime video/wvc1
W/VideoCapabilities(  417): Unsupported mime video/x-ms-wmv
W/VideoCapabilities(  417): Unsupported mime video/x-ms-wmv7
W/VideoCapabilities(  417): Unsupported mime video/x-ms-wmv8
W/VideoCapabilities(  417): Unsupported mime video/mp43
W/VideoCapabilities(  417): Unsupported mime video/sorenson
W/VideoCapabilities(  417): Unsupported mime video/mp4v-esdp
D/ConnectivityManager.CallbackHandler(  417): CM callback handler got msg 524295
D/ConnectivityManager.CallbackHandler(  417): CM callback handler got msg 524295
I/VideoCapabilities(  417): Unsupported profile 4 for video/mp4v-es
W/AudioCapabilities(  417): Unsupported mime audio/ac3
D/Activity(  417): performCreate Call secproduct feature valuefalse
D/Activity(  417): performCreate Call debug elastic valuetrue
D/OpenGLRenderer(  417): Render dirty regions requested: true
I/Choreographer(  417): Skipped 75 frames!  The application may be doing too much work on its main thread.
I/OpenGLRenderer(  417): Initialized EGL, version 1.4
D/OpenGLRenderer(  417): Enabling debug mode 0
D/ConnectivityManager.CallbackHandler(  417): CM callback handler got msg 524290
W/cr_BindingManager(  417): Cannot call determinedVisibility() - never saw a connection for the pid: 417
I/tei (  417): Uno.NullReferenceException: Object reference was null
D/tei (  417): Uno.NullReferenceException: Object reference was null
D/AndroidRuntime(  417): Shutting down VM
E/AndroidRuntime(  417): FATAL EXCEPTION: main
E/AndroidRuntime(  417): Process: com.tei, PID: 417
E/AndroidRuntime(  417): java.lang.RuntimeException: Uno.NullReferenceException: Object reference was null
E/AndroidRuntime(  417): 	at com.Bindings.ExternedBlockHost.callUno_Uno_Platform_AndroidDisplay_OnFrameCallback55(Native Method)
E/AndroidRuntime(  417): 	at com.foreign.Uno.Platform.AndroidDisplay$1.doFrame(AndroidDisplay.java:55)
E/AndroidRuntime(  417): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:775)
E/AndroidRuntime(  417): 	at android.view.Choreographer.doCallbacks(Choreographer.java:590)
E/AndroidRuntime(  417): 	at android.view.Choreographer.doFrame(Choreographer.java:559)
E/AndroidRuntime(  417): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
E/AndroidRuntime(  417): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(  417): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(  417): 	at android.os.Looper.loop(Looper.java:145)
E/AndroidRuntime(  417): 	at android.app.ActivityThread.main(ActivityThread.java:5951)
E/AndroidRuntime(  417): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(  417): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(  417): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
E/AndroidRuntime(  417): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
I/Process (  417): Sending signal. PID: 417 SIG: 9
I/ActivityManager(  905): Process com.tei (pid 417)(adj 15) has died(84,523)
Process com.tei terminated.
```

**Comment by kusma** [comment]
Can you please build with -DCPPSTACKTRACE and post the stack traces for the NullReferenceExceptions?

**Comment by ckarmy** [comment]
I get this:

```
fuse build --target=Android --run -DCPPSTACKTRACE
Uno 1.1.3 (build 5510) macOS 10.12 i386 933ea5b

Configuring (3.7 s)
Compiling syntax tree (2.9 s)
Generating code and data (13.3 s)
Building Android app
2/2: Ptei.apk
(1:24)

Build completed in 104.84 seconds

---
Installing APK on 1 device(s)
Launching activity 'Ptei'
Running logcat on 'e21b5b8a'
E/Zygote  (18396): MountEmulatedStorage()
E/Zygote  (18396): v2
I/SELinux (18396): Function: selinux_compare_spd_ram, SPD-policy is existed. and_ver=SEPF_GT-I9505_5.0.1-1 ver=51
I/SELinux (18396): Function: selinux_compare_spd_ram , priority [1] , priority version is VE=SEPF_GT-I9505_5.0.1-1_0051
E/SELinux (18396): [DEBUG] get_category: variable seinfo: default sensitivity: NULL, cateogry: NULL
I/art     (18396): Late-enabling -Xcheck:jni
I/libpersona(18396): KNOX_SDCARD checking this for 10226
I/libpersona(18396): KNOX_SDCARD not a persona
I/ActivityManager(  905): Start proc com.Ptei for activity com.Ptei/.Ptei: pid=18396 uid=10226 gids={50226, 9997, 1028, 1015, 3003} abi=armeabi-v7a
D/ResourcesManager(18396): creating new AssetManager and set to /data/app/com.Ptei-1/base.apk
D/Ptei (18396): SDK: 21
I/Adreno-EGL(18396): <qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build:  ()
I/Adreno-EGL(18396): OpenGL ES Shader Compiler Version: E031.25.03.06
I/Adreno-EGL(18396): Build Date: 01/24/15 Sat
I/Adreno-EGL(18396): Local Branch: AF11_RB1_AU15
I/Adreno-EGL(18396): Remote Branch: 
I/Adreno-EGL(18396): Local Patches: 
I/Adreno-EGL(18396): Reconstruct Branch: 
W/InstanceID/Rpc(18396): Found 10036
I/WebViewFactory(18396): Loading com.google.android.webview version 59.0.3071.125 (code 307112500)
D/ResourcesManager(18396): creating new AssetManager and set to /data/app/com.google.android.webview-1/base.apk
I/art     (18396): Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.TokenBindingManagerAdapter>
I/art     (18396): Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.TokenBindingManagerAdapter>
I/art     (18396): Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.ServiceWorkerControllerAdapter>
I/art     (18396): Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.ServiceWorkerControllerAdapter>
I/cr_LibraryLoader(18396): Time to load native libraries: 1 ms (timestamps 8362-8363)
I/chromium(18396): [INFO:library_loader_hooks.cc(144)] Chromium logging enabled: level = 0, default verbosity = 0
I/cr_LibraryLoader(18396): Expected native library version number "59.0.3071.125", actual native library version number "59.0.3071.125"
I/cr_BrowserStartup(18396): Initializing chromium process, singleProcess=true
I/art     (18396): Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.WebViewContentsClientAdapter$WebResourceErrorImpl>
I/art     (18396): Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.WebViewContentsClientAdapter$WebResourceErrorImpl>
W/cr_BindingManager(18396): Cannot setInForeground() - never saw a connection for the pid: 18396
D/ConnectivityManager.CallbackHandler(18396): CM callback handler got msg 524290
I/art     (18396): Rejecting re-init on previously-failed class java.lang.Class<org.chromium.content.browser.FloatingActionModeCallback>
I/art     (18396): Rejecting re-init on previously-failed class java.lang.Class<org.chromium.content.browser.FloatingActionModeCallback>
W/cr_media(18396): Requires BLUETOOTH permission
E/libEGL  (18396): validate_display:255 error 3008 (EGL_BAD_DISPLAY)
W/AudioCapabilities(18396): Unsupported mime audio/mpeg-L1
W/AudioCapabilities(18396): Unsupported mime audio/mpeg-L2
W/AudioCapabilities(18396): Unsupported mime audio/x-ms-wma
W/AudioCapabilities(18396): Unsupported mime audio/x-ima
W/AudioCapabilities(18396): Unsupported mime audio/qcelp
W/AudioCapabilities(18396): Unsupported mime audio/evrc
W/VideoCapabilities(18396): Unsupported mime video/wvc1
W/VideoCapabilities(18396): Unsupported mime video/x-ms-wmv
W/VideoCapabilities(18396): Unrecognized profile/level 32768/2 for video/mp4v-es
W/VideoCapabilities(18396): Unsupported mime video/wvc1
W/VideoCapabilities(18396): Unsupported mime video/x-ms-wmv
W/VideoCapabilities(18396): Unsupported mime video/x-ms-wmv7
W/VideoCapabilities(18396): Unsupported mime video/x-ms-wmv8
W/VideoCapabilities(18396): Unsupported mime video/mp43
W/VideoCapabilities(18396): Unsupported mime video/sorenson
W/VideoCapabilities(18396): Unsupported mime video/mp4v-esdp
I/VideoCapabilities(18396): Unsupported profile 4 for video/mp4v-es
W/AudioCapabilities(18396): Unsupported mime audio/ac3
D/Activity(18396): performCreate Call secproduct feature valuefalse
D/Activity(18396): performCreate Call debug elastic valuetrue
D/OpenGLRenderer(18396): Render dirty regions requested: true
I/Choreographer(18396): Skipped 73 frames!  The application may be doing too much work on its main thread.
I/OpenGLRenderer(18396): Initialized EGL, version 1.4
D/OpenGLRenderer(18396): Enabling debug mode 0
V/ActivityThread(18396): updateVisibility : ActivityRecord{28ec6e9e token=android.os.BinderProxy@1264f2a1 {com.Ptei/com.Ptei.Ptei}} show : true
D/ConnectivityManager.CallbackHandler(18396): CM callback handler got msg 524290
W/cr_BindingManager(18396): Cannot call determinedVisibility() - never saw a connection for the pid: 18396
I/Ptei (18396): Uno.NullReferenceException: Object reference was null
I/Ptei (18396):    at Fuse.Triggers.Actions.EvaluateJS.Execute()
I/Ptei (18396):    at Fuse.Triggers.Actions.EvaluateJS.Perform(Fuse.Node)
I/Ptei (18396):    at Fuse.Triggers.Actions.TriggerAction.PerformFromNode(Fuse.Node)
I/Ptei (18396):    at Fuse.Triggers.Trigger.DeferredItem.Perform()
I/Ptei (18396):    at Fuse.UpdateManager.ProcessDeferredActions(Fuse.Stage,Uno.Collections.List<Uno.Exception>&)
I/Ptei (18396):    at Fuse.UpdateManager.Update(Fuse.Stage)
I/Ptei (18396):    at Fuse.UpdateManager.ProcessStages()
I/Ptei (18396):    at Fuse.UpdateManager.Update()
I/Ptei (18396):    at Fuse.App.OnTick(object,Uno.Platform.TimerEventArgs)
I/Ptei (18396):    at Uno.Platform.Display.OnTick(Uno.Platform.TimerEventArgs)
I/Ptei (18396):    at Uno.Platform.AndroidDisplay.OnFrameCallback(double,double)
D/Ptei (18396): Uno.NullReferenceException: Object reference was null
D/Ptei (18396):    at Fuse.Triggers.Actions.EvaluateJS.Execute()
D/Ptei (18396):    at Fuse.Triggers.Actions.EvaluateJS.Perform(Fuse.Node)
D/Ptei (18396):    at Fuse.Triggers.Actions.TriggerAction.PerformFromNode(Fuse.Node)
D/Ptei (18396):    at Fuse.Triggers.Trigger.DeferredItem.Perform()
D/Ptei (18396):    at Fuse.UpdateManager.ProcessDeferredActions(Fuse.Stage,Uno.Collections.List<Uno.Exception>&)
D/Ptei (18396):    at Fuse.UpdateManager.Update(Fuse.Stage)
D/Ptei (18396):    at Fuse.UpdateManager.ProcessStages()
D/Ptei (18396):    at Fuse.UpdateManager.Update()
D/Ptei (18396):    at Fuse.App.OnTick(object,Uno.Platform.TimerEventArgs)
D/Ptei (18396):    at Uno.Platform.Display.OnTick(Uno.Platform.TimerEventArgs)
D/Ptei (18396):    at Uno.Platform.AndroidDisplay.OnFrameCallback(double,double)
D/AndroidRuntime(18396): Shutting down VM
E/AndroidRuntime(18396): FATAL EXCEPTION: main
E/AndroidRuntime(18396): Process: com.Ptei, PID: 18396
E/AndroidRuntime(18396): java.lang.RuntimeException: Uno.NullReferenceException: Object reference was null
E/AndroidRuntime(18396):    at Fuse.Triggers.Actions.EvaluateJS.Execute()
E/AndroidRuntime(18396):    at Fuse.Triggers.Actions.EvaluateJS.Perform(Fuse.Node)
E/AndroidRuntime(18396):    at Fuse.Triggers.Actions.TriggerAction.PerformFromNode(Fuse.Node)
E/AndroidRuntime(18396):    at Fuse.Triggers.Trigger.DeferredItem.Perform()
E/AndroidRuntime(18396):    at Fuse.UpdateManager.ProcessDeferredActions(Fuse.Stage,Uno.Collections.List<Uno.Exception>&)
E/AndroidRuntime(18396):    at Fuse.UpdateManager.Update(Fuse.Stage)
E/AndroidRuntime(18396):    at Fuse.UpdateManager.ProcessStages()
E/AndroidRuntime(18396):    at Fuse.UpdateManager.Update()
E/AndroidRuntime(18396):    at Fuse.App.OnTick(object,Uno.Platform.TimerEventArgs)
E/AndroidRuntime(18396):    at Uno.Platform.Display.OnTick(Uno.Platform.TimerEventArgs)
E/AndroidRuntime(18396):    at Uno.Platform.AndroidDisplay.OnFrameCallback(double,double)
E/AndroidRuntime(18396): 	at com.Bindings.ExternedBlockHost.callUno_Uno_Platform_AndroidDisplay_OnFrameCallback55(Native Method)
E/AndroidRuntime(18396): 	at com.foreign.Uno.Platform.AndroidDisplay$1.doFrame(AndroidDisplay.java:55)
E/AndroidRuntime(18396): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:775)
E/AndroidRuntime(18396): 	at android.view.Choreographer.doCallbacks(Choreographer.java:590)
E/AndroidRuntime(18396): 	at android.view.Choreographer.doFrame(Choreographer.java:559)
E/AndroidRuntime(18396): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
E/AndroidRuntime(18396): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(18396): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(18396): 	at android.os.Looper.loop(Looper.java:145)
E/AndroidRuntime(18396): 	at android.app.ActivityThread.main(ActivityThread.java:5951)
E/AndroidRuntime(18396): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(18396): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(18396): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
E/AndroidRuntime(18396): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
I/Process (18396): Sending signal. PID: 18396 SIG: 9
I/ActivityManager(  905): Process com.Ptei (pid 18396)(adj 9) has died(68,518)
Process com.Ptei terminated.
```

**Comment by ckarmy** [comment]
I get the same crash on 3f3fb2a

**Comment by ckarmy** [comment]
In the stable version (1.1.1 13893) work fine!

**Comment by kusma** [comment]
@mortoray: Assigning you, because you're the only one who changed `Fuse.Triggers.Actions.EvaluateJS` since release-1.1...

**Comment by mortoray** [comment]
@ckarmy You can test if that PR branch fixes the issue for you.

**Comment by ckarmy** [comment]
Yes! Problem solved! Thanks!

**Comment by kusma** [comment]
@ckarmy: thanks a lot for letting us know!
