### ISSUE TITLE
Massive stall on Asus Nexus 7

### ISSUE THREAD

**Issue by nekronos** [fusetools/fuselibs-public#397]
On Asus Nexus 7 with Adreno 320 and Android Kitkat we sometimes get massive stalls while rendering. I have observed everything between 8 to 80 seconds long stalls. I have only reproduced this on that device. For example, this is not reproducible on Samsung Galaxy S4 with Kitkat and Adreno 320.

During a stall all the time is spent in either 
- `new framebuffer()`
- `glViewport`
- `glSwapbuffers`

Also during a stall I would sometimes get `GL_OUT_OF_MEMORY` in the log and one of the stack traces below. This does not crash the app and does not give any visual glitches.

```
"main" prio=5 tid=1 NATIVE
  | group="main" sCount=1 dsCount=0 obj=0x41575c90 self=0x414af408
  | sysTid=9170 nice=0 sched=0/0 cgrp=apps handle=1074213204
  | state=S schedstat=( 0 0 0 ) utm=1075 stm=104 core=1
  #00  pc 00020588  /system/lib/libc.so (__ioctl+8)
  #01  pc 0002cb37  /system/lib/libc.so (ioctl+14)
  #02  pc 0000c6c9  /system/lib/libgsl.so (gsl_ldd_control+156)
  #03  pc 0000cc09  /system/lib/libgsl.so (ioctl_kgsl_cmdstream_issueibcmds+64)
  #04  pc 000052f3  /system/lib/libgsl.so (gsl_command_issueib_sync+186)
  #05  pc 00070cff  /system/lib/egl/libGLESv2_adreno.so (rb_cmdbuffer_issue+1134)
  #06  pc 00077533  /system/lib/egl/libGLESv2_adreno.so (rb_perform_binning_resolve+1534)
  #07  pc 00077d5f  /system/lib/egl/libGLESv2_adreno.so (rb_perform_resolve+262)
  #08  pc 000780e5  /system/lib/egl/libGLESv2_adreno.so (rb_resolve+364)
  #09  pc 000555a5  /system/lib/egl/libGLESv2_adreno.so
  #10  pc 00055a23  /system/lib/egl/libGLESv2_adreno.so (deferred_glBindFramebuffer+18)
  #11  pc 0005079f  /system/lib/egl/libGLESv2_adreno.so
  #12  pc 000508e9  /system/lib/egl/libGLESv2_adreno.so (deferred_op_queue_flush+192)
  #13  pc 000608ef  /system/lib/egl/libGLESv2_adreno.so (core_glViewport+14)
  #14  pc 00041fa9  /system/lib/egl/libGLESv2_adreno.so (glViewport+28)
  #15  pc 00021a87  /system/lib/libEGL.so
  #16  pc 005a1147  /data/app-lib/com.fuseapp.mobile-1/libFuseApp.so (g::OpenGL::GL::Viewport(int, int, int, int)+40)
  #17  pc 0065b62d  /data/app-lib/com.fuseapp.mobile-1/libFuseApp.so (g::Fuse::DrawContext::GLViewportPixelSize(g::Uno::Int2)+108)
  #18  pc 0065b82b  /data/app-lib/com.fuseapp.mobile-1/libFuseApp.so (g::Fuse::DrawContext::PopRenderTarget()+158)
  #19  pc 007c1477  /data/app-lib/com.fuseapp.mobile-1/libFuseApp.so (g::Fuse::Effects::EffectHelpers::BlurVertical(g::Fuse::DrawContext*, g::Uno::Int2, g::Uno::Graphics::Texture2D*, float, int)+214)
  #20  pc 007bdfdb  /data/app-lib/com.fuseapp.mobile-1/libFuseApp.so (g::Fuse::Effects::EffectHelpers::Blur(g::Uno::Graphics::Texture2D*, g::Fuse::DrawContext*, float)+702)
  #21  pc 007bf303  /data/app-lib/com.fuseapp.mobile-1/libFuseApp.so (g::Fuse::Effects::DropShadow__OnRender_fn(g::Fuse::Effects::DropShadow*, g::Fuse::DrawContext*, g::Uno::Rect*)+266)
  #22  pc 007bbd3d  /data/app-lib/com.fuseapp.mobile-1/libFuseApp.so (g::Fuse::Effects::BasicEffect::OnRender(g::Fuse::DrawContext*, g::Uno::Rect)+88)
  #23  pc 007bb8df  /data/app-lib/com.fuseapp.mobile-1/libFuseApp.so (g::Fuse::Effects::BasicEffect__Render_fn(g::Fuse::Effects::BasicEffect*, g::Fuse::DrawContext*)+98)
  #24  pc 007a8397  /data/app-lib/com.fuseapp.mobile-1/libFuseApp.so (g::Fuse::Effects::Effect::Render(g::Fuse::DrawContext*)+28)
  #25  pc 0079e57b  /data/app-lib/com.fuseapp.mobile-1/libFuseApp.so (g::Fuse::Elements::Element::CompositEffects(g::Fuse::DrawContext*)+322)
  at com.Bindings.ExternedBlockHost.callUno_Uno_Platform_AndroidDisplay_OnFrameCallback55(Native Method)
  at com.foreign.Uno.Platform.AndroidDisplay$1.doFrame(AndroidDisplay.java:55)
  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:747)
  at android.view.Choreographer.doCallbacks(Choreographer.java:562)
  at android.view.Choreographer.doFrame(Choreographer.java:531)
  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
  at android.os.Handler.handleCallback(Handler.java:733)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:137)
  at android.app.ActivityThread.main(ActivityThread.java:4998)
  at java.lang.reflect.Method.invokeNative(Native Method)
  at java.lang.reflect.Method.invoke(Method.java:515)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:777)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:593)
at dalvik.system.NativeStart.main(Native Method)
```
```
"main" prio=5 tid=1 NATIVE
  | group="main" sCount=1 dsCount=0 obj=0x41575c90 self=0x414af408
  | sysTid=9170 nice=0 sched=0/0 cgrp=apps handle=1074213204
  | state=S schedstat=( 0 0 0 ) utm=2661 stm=315 core=1
  #00  pc 00020588  /system/lib/libc.so (__ioctl+8)
  #01  pc 0002cb37  /system/lib/libc.so (ioctl+14)
  #02  pc 0000c6c9  /system/lib/libgsl.so (gsl_ldd_control+156)
  #03  pc 0000cc09  /system/lib/libgsl.so (ioctl_kgsl_cmdstream_issueibcmds+64)
  #04  pc 000052f3  /system/lib/libgsl.so (gsl_command_issueib_sync+186)
  #05  pc 00070cff  /system/lib/egl/libGLESv2_adreno.so (rb_cmdbuffer_issue+1134)
  #06  pc 00077487  /system/lib/egl/libGLESv2_adreno.so (rb_perform_binning_resolve+1362)
  #07  pc 00077d5f  /system/lib/egl/libGLESv2_adreno.so (rb_perform_resolve+262)
  #08  pc 000780e5  /system/lib/egl/libGLESv2_adreno.so (rb_resolve+364)
  #09  pc 0007c75b  /system/lib/egl/libGLESv2_adreno.so (rb_surface_swap+214)
  #10  pc 00060d2d  /system/lib/egl/libGLESv2_adreno.so (gl2_surface_swap+72)
  #11  pc 000524f9  /system/lib/egl/libGLESv2_adreno.so (oglSwapBuffer+148)
  #12  pc 00012c18  /system/lib/egl/libEGL_adreno.so (qeglDrvAPI_eglSwapBuffers+1864)
  #13  pc 00006bd0  /system/lib/egl/libEGL_adreno.so (eglSwapBuffers+16)
  #14  pc 0000f67d  /system/lib/libEGL.so (eglSwapBuffers+280)
  #15  pc 00457abd  /data/app-lib/com.fuseapp.mobile-1/libFuseApp.so (GLHelper::SwapBuffers(void*)+28)
  #16  pc 008269cb  /data/app-lib/com.fuseapp.mobile-1/libFuseApp.so (g::Fuse::Controls::Native::Android::GraphicsViewBase::EndDraw()+14)
  #17  pc 00826859  /data/app-lib/com.fuseapp.mobile-1/libFuseApp.so (g::Fuse::Controls::Native::Android::GraphicsViewBase__EndDraw_fn(g::Fuse::Controls::Native::Android::GraphicsViewBase*)+12)
  #18  pc 007d954d  /data/app-lib/com.fuseapp.mobile-1/libFuseApp.so (g::Fuse::Controls::Native::IGraphicsView::EndDraw(uInterface const&)+30)
  #19  pc 007d8d51  /data/app-lib/com.fuseapp.mobile-1/libFuseApp.so (g::Fuse::Controls::GraphicsView::DrawFrame()+624)
  #20  pc 007d8ad9  /data/app-lib/com.fuseapp.mobile-1/libFuseApp.so (g::Fuse::Controls::GraphicsView__DrawFrame_fn(g::Fuse::Controls::GraphicsView*)+12)
  #21  pc 00452c41  /data/app-lib/com.fuseapp.mobile-1/libFuseApp.so (uDelegate::InvokeVoid()+152)
  #22  pc 006835a3  /data/app-lib/com.fuseapp.mobile-1/libFuseApp.so (g::Fuse::UpdateListener::Invoke()+66)
  #23  pc 00684535  /data/app-lib/com.fuseapp.mobile-1/libFuseApp.so (g::Fuse::UpdateManager::ProcessOnces(g::Fuse::Stage*, g::Uno::Collections::List**)+268)
  at com.Bindings.ExternedBlockHost.callUno_Uno_Platform_AndroidDisplay_OnFrameCallback55(Native Method)
  at com.foreign.Uno.Platform.AndroidDisplay$1.doFrame(AndroidDisplay.java:55)
  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:747)
  at android.view.Choreographer.doCallbacks(Choreographer.java:562)
  at android.view.Choreographer.doFrame(Choreographer.java:531)
  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
  at android.os.Handler.handleCallback(Handler.java:733)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:137)
  at android.app.ActivityThread.main(ActivityThread.java:4998)
  at java.lang.reflect.Method.invokeNative(Native Method)
  at java.lang.reflect.Method.invoke(Method.java:515)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:777)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:593)
at dalvik.system.NativeStart.main(Native Method)
```
-------------------
The app used for testing cannot be uploaded publicly. I am working on a test app that I will upload later. 

When does a stall trigger
* When an infinite `ScrollView` triggers load of more items
    - Image texture upload
    - Init of DropShadow, elements with Opacity
    - Animating Colors/Gradients
* Transitions with many animations. Animating Colors, Opacity, Layout etc

Common for all stall is that they involve rendering to a `framebuffer`. For example:
* Animating Opacity
* Rendering DropShadow
* Rendering LinearGradient
* Rendering Masks
* Drawing to CacheFramebuffers

My best guess is that we end up with texture ghosting. The cases for stall mentioned above all involve touching framebuffers that might be used in pending frames. Resulting in lots of copies on the GPU. (Whats described in [Imaginations](https://www.imgtec.com/blog/how-to-improve-your-renderer-on-powervr-based-platforms/) blogpost on texture ghosting matches well with what I observe). 

Another observation backing this theory is if the OS backbutton is clicked during a stall, the stall will halt and the app will continue. Guessing that the OS backbutton drops all pending frames since the OS/App should "go back" anyways.

Disabling Opacity, Caching, DropShadow, Mask and LinearGradient (basically no framebuffers will be touched in the app I am testing with) makes the app never stall. The frametimes are then from 8-40 ms.

----------------------------------------------
Working on a test app where I will draw to framebuffers and draw with those buffers every frame. This should hopefully prove/disprove my theory.

**Comment by danhollick** [comment]
To be fair, I have one of these tablets and it is ridiculously slow with a lot of apps. Is it unique to a Fuse app?

**Comment by nekronos** [comment]
Havent really tested other apps except for Chrome. Which is fast-ish. Anyways, thanks for pointing it out. I should test other non-trivial apps.

**Comment by danhollick** [comment]
Yeah, I mainly use it as netflix remote for my Chromecast and it regulary hangs in both the Google Home app, and the netflix app.
