### ISSUE TITLE
fuse-modalview example crashes due to seemingly bad linked-list management

### ISSUE THREAD

**Issue by kusma** [fusetools/fuselibs-public#528]
The example-project from [fuse-modalview](https://github.com/bolav/fuse-modalview) crashes after pressing "A button" and then either "Ok" or "Cancel", with the following stack-trace:

```
System.Exception: Node already has a parent - can only have one
   at Fuse.Visual.Children_MakeParent(Visual parent, Node child) in C:\Users\erik\src\fuselibs\Source\Fuse.Nodes\Visual.Children.LinkedList.uno:line 56
   at Fuse.Visual.Children_Add(Node n) in C:\Users\erik\src\fuselibs\Source\Fuse.Nodes\Visual.Children.LinkedList.uno:line 95
   at Fuse.Visual.Add(Node item) in C:\Users\erik\src\fuselibs\Source\Fuse.Nodes\Visual.Children.uno:line 180
   at Bolav.Modal.ModalJS.RemoveModalUX() in C:\Users\erik\src\fuse-modalview\ModalJS.uno:line 125
   at Fuse.UpdateManager.ProcessPostActionsImpl() in C:\Users\erik\src\fuselibs\Source\Fuse.Common\UpdateManager.uno:line 476
```

However, adding instrumenting to the code shows that the child being added does indeed have `Node.Parent = null`. So it seems something is up with our linked-list code.

**Comment by kusma** [comment]
This seems to fix the problem:
```patch
diff --git a/Source/Fuse.Nodes/Visual.Children.uno b/Source/Fuse.Nodes/Visual.Children.uno
index 45e637e..c706e15 100644
--- a/Source/Fuse.Nodes/Visual.Children.uno
+++ b/Source/Fuse.Nodes/Visual.Children.uno
@@ -170,7 +170,10 @@ namespace Fuse
 		void ICollection<Node>.Clear()
 		{
 			for (var c = _firstChild; c != null; c = c._nextSibling)
+			{
+				Children_MakeOrphan(c);
 				OnRemoved(c);
+			}
 			Children_Clear();
 		}
```

**Comment by kusma** [comment]
Hmm, this shouldn't be needed, as `Children_Clear() calls `Children_MakeOrphan()` for all children...
