### ISSUE TITLE
Models: differ crash

### ISSUE THREAD

**Issue by nekronos** [fusetools/fuselibs-public#731]
```
Error: Fuse.Scripting.ScriptException: Name: TypeError: Cannot read property '__fuse_id' of null
Error message: Uncaught TypeError: Cannot read property '__fuse_id' of null
File name: 3rdparty/zone.min.js
Line number: 196
Source line: 						throw error;
JS stack trace: TypeError: Cannot read property '__fuse_id' of null
    at update (FuseJS/Model.js:363:52)
    at Object.meta.diff (FuseJS/Model.js:263:6)
    at FuseJS/Model.js:209:11
    at ZoneDelegate.invokeTask (3rdparty/zone.min.js:425:19)
    at Zone.runTask (3rdparty/zone.min.js:192:32)
    at ZoneTask.invokeTask (3rdparty/zone.min.js:499:22)
    at ZoneTask.invoke (3rdparty/zone.min.js:488:33)
    at timer (3rdparty/zone.min.js:2040:17)

   at Fuse.Scripting.V8.Context.OnScriptException(Fuse.Scripting.V8.Simple.JSScriptException)
   at Fuse.Scripting.V8.Error.Check(Fuse.Scripting.V8.Simple.JSContext,Fuse.Scripting.V8.Simple.JSScriptException,Uno.Action<Fuse.Scripting.V8.Simple.JSScriptException>)
   at Fuse.Scripting.V8.V8SimpleExtensions.Call(Fuse.Scripting.V8.Simple.JSFunction,Fuse.Scripting.V8.Simple.JSContext,Fuse.Scripting.V8.Simple.JSObject,Fuse.Scripting.V8.Simple.JSValue[],Fuse.Scripting.V8.AutoReleasePool,Uno.Action<Fuse.Scripting.V8.Simple.JSScriptException>)
   at Fuse.Scripting.V8.Function.Call(Fuse.Scripting.Context,object[])
   at Fuse.Reactive.FuseJS.TimerModule.CallbackClosure.Callback(Fuse.Scripting.Context)
   at Fuse.Reactive.FuseJS.TimerManager.Timer.Update(Fuse.Scripting.Context)
   at Fuse.Reactive.FuseJS.TimerManager.Tick(Fuse.Scripting.Context)
   at Fuse.Reactive.FuseJS.TimerModule.UpdateModule(Fuse.Scripting.Context)
   at Fuse.Reactive.FuseJS.Builtins.UpdateModules(Fuse.Scripting.Context)
   at Fuse.Scripting.JavaScript.ThreadWorker.RunOnce(Fuse.Scripting.JavaScript.JSContext)
   at Fuse.Scripting.JavaScript.ThreadWorker.RunInner(Fuse.Scripting.JavaScript.JSContext)
   at Fuse.Scripting.JavaScript.ThreadWorker.Run()
Fatal: Unhandled Exception: Fuse.Scripting.ScriptException: Name: TypeError: Cannot read property '__fuse_id' of null
Error message: Uncaught TypeError: Cannot read property '__fuse_id' of null
File name: 3rdparty/zone.min.js
Line number: 196
Source line: 						throw error;
JS stack trace: TypeError: Cannot read property '__fuse_id' of null
    at update (FuseJS/Model.js:363:52)
    at Object.meta.diff (FuseJS/Model.js:263:6)
    at FuseJS/Model.js:209:11
    at ZoneDelegate.invokeTask (3rdparty/zone.min.js:425:19)
    at Zone.runTask (3rdparty/zone.min.js:192:32)
    at ZoneTask.invokeTask (3rdparty/zone.min.js:499:22)
    at ZoneTask.invoke (3rdparty/zone.min.js:488:33)
    at timer (3rdparty/zone.min.js:2040:17)

   at Fuse.Scripting.V8.Context.OnScriptException(Fuse.Scripting.V8.Simple.JSScriptException)
   at Fuse.Scripting.V8.Error.Check(Fuse.Scripting.V8.Simple.JSContext,Fuse.Scripting.V8.Simple.JSScriptException,Uno.Action<Fuse.Scripting.V8.Simple.JSScriptException>)
   at Fuse.Scripting.V8.V8SimpleExtensions.Call(Fuse.Scripting.V8.Simple.JSFunction,Fuse.Scripting.V8.Simple.JSContext,Fuse.Scripting.V8.Simple.JSObject,Fuse.Scripting.V8.Simple.JSValue[],Fuse.Scripting.V8.AutoReleasePool,Uno.Action<Fuse.Scripting.V8.Simple.JSScriptException>)
   at Fuse.Scripting.V8.Function.Call(Fuse.Scripting.Context,object[])
   at Fuse.Reactive.FuseJS.TimerModule.CallbackClosure.Callback(Fuse.Scripting.Context)
   at Fuse.Reactive.FuseJS.TimerManager.Timer.Update(Fuse.Scripting.Context)
   at Fuse.Reactive.FuseJS.TimerManager.Tick(Fuse.Scripting.Context)
   at Fuse.Reactive.FuseJS.TimerModule.UpdateModule(Fuse.Scripting.Context)
   at Fuse.Reactive.FuseJS.Builtins.UpdateModules(Fuse.Scripting.Context)
   at Fuse.Scripting.JavaScript.ThreadWorker.RunOnce(Fuse.Scripting.JavaScript.JSContext)
   at Fuse.Scripting.JavaScript.ThreadWorker.RunInner(Fuse.Scripting.JavaScript.JSContext)
   at Fuse.Scripting.JavaScript.ThreadWorker.Run()

Function: void g::Fuse::AppBase::OnUnhandledException(::g::Uno::Exception *, bool)
Line: 748
```

**Comment by nekronos** [comment]
Steps to reproduce:
1. Build & run: [Archive.zip](https://github.com/fusetools/fuselibs-public/files/1466962/Archive.zip)
2. Click a list item on the first page
3. Observe crash

**Comment by sebbert** [comment]
Fixed in https://github.com/fusetools/fuselibs-public/pull/601/commits/ede3506371b0f18b3dc606627915e40d2646387f
