### ISSUE TITLE
Models: index out of bounds in ArrayMirror

### ISSUE THREAD

**Issue by nekronos** [fusetools/fuselibs-public#732]
```
Error: Uno.IndexOutOfRangeException: Index out of range
   at Uno.Collections.List`1.BoundsCheck(int)
   at Uno.Collections.List`1.get_Item(int)
   at Fuse.Scripting.JavaScript.ArrayMirror.get_Item(int)
   at Fuse.Scripting.JavaScript.TreeObservable.Operation.Perform(Fuse.Scripting.Context,object,int)
   at Fuse.Scripting.JavaScript.TreeObservable.Operation.Perform(Fuse.Scripting.Context,object,int)
   at Fuse.Scripting.JavaScript.TreeObservable.Operation.Perform(Fuse.Scripting.Context,object,int)
   at Fuse.Scripting.JavaScript.TreeObservable.Operation.Perform(Fuse.Scripting.Context)
   at Fuse.Scripting.JavaScript.TreeObservable.Set(Fuse.Scripting.Context,object[])
   at Fuse.Scripting.V8.Marshaller.CallbackWrapper.Call(Fuse.Scripting.V8.Simple.JSValue[],Fuse.Scripting.V8.Simple.JSValue&)
   at Fuse.Scripting.V8.V8SimpleExtensions.Call(Fuse.Scripting.V8.Simple.JSFunction,Fuse.Scripting.V8.Simple.JSContext,Fuse.Scripting.V8.Simple.JSObject,Fuse.Scripting.V8.Simple.JSValue[],Fuse.Scripting.V8.AutoReleasePool,Uno.Action<Fuse.Scripting.V8.Simple.JSScriptException>)
   at Fuse.Scripting.V8.Function.Call(Fuse.Scripting.Context,object[])
   at Fuse.Reactive.FuseJS.TimerModule.CallbackClosure.Callback(Fuse.Scripting.Context)
   at Fuse.Reactive.FuseJS.TimerManager.Timer.Update(Fuse.Scripting.Context)
   at Fuse.Reactive.FuseJS.TimerManager.Tick(Fuse.Scripting.Context)
   at Fuse.Reactive.FuseJS.TimerModule.UpdateModule(Fuse.Scripting.Context)
   at Fuse.Reactive.FuseJS.Builtins.UpdateModules(Fuse.Scripting.Context)
   at Fuse.Scripting.JavaScript.ThreadWorker.RunOnce(Fuse.Scripting.JavaScript.JSContext)
   at Fuse.Scripting.JavaScript.ThreadWorker.RunInner(Fuse.Scripting.JavaScript.JSContext)
   at Fuse.Scripting.JavaScript.ThreadWorker.Run()
Fatal: Unhandled Exception: Uno.IndexOutOfRangeException: Index out of range
   at Uno.Collections.List`1.BoundsCheck(int)
   at Uno.Collections.List`1.get_Item(int)
   at Fuse.Scripting.JavaScript.ArrayMirror.get_Item(int)
   at Fuse.Scripting.JavaScript.TreeObservable.Operation.Perform(Fuse.Scripting.Context,object,int)
   at Fuse.Scripting.JavaScript.TreeObservable.Operation.Perform(Fuse.Scripting.Context,object,int)
   at Fuse.Scripting.JavaScript.TreeObservable.Operation.Perform(Fuse.Scripting.Context,object,int)
   at Fuse.Scripting.JavaScript.TreeObservable.Operation.Perform(Fuse.Scripting.Context)
   at Fuse.Scripting.JavaScript.TreeObservable.Set(Fuse.Scripting.Context,object[])
   at Fuse.Scripting.V8.Marshaller.CallbackWrapper.Call(Fuse.Scripting.V8.Simple.JSValue[],Fuse.Scripting.V8.Simple.JSValue&)
   at Fuse.Scripting.V8.V8SimpleExtensions.Call(Fuse.Scripting.V8.Simple.JSFunction,Fuse.Scripting.V8.Simple.JSContext,Fuse.Scripting.V8.Simple.JSObject,Fuse.Scripting.V8.Simple.JSValue[],Fuse.Scripting.V8.AutoReleasePool,Uno.Action<Fuse.Scripting.V8.Simple.JSScriptException>)
   at Fuse.Scripting.V8.Function.Call(Fuse.Scripting.Context,object[])
   at Fuse.Reactive.FuseJS.TimerModule.CallbackClosure.Callback(Fuse.Scripting.Context)
   at Fuse.Reactive.FuseJS.TimerManager.Timer.Update(Fuse.Scripting.Context)
   at Fuse.Reactive.FuseJS.TimerManager.Tick(Fuse.Scripting.Context)
   at Fuse.Reactive.FuseJS.TimerModule.UpdateModule(Fuse.Scripting.Context)
   at Fuse.Reactive.FuseJS.Builtins.UpdateModules(Fuse.Scripting.Context)
   at Fuse.Scripting.JavaScript.ThreadWorker.RunOnce(Fuse.Scripting.JavaScript.JSContext)
   at Fuse.Scripting.JavaScript.ThreadWorker.RunInner(Fuse.Scripting.JavaScript.JSContext)
   at Fuse.Scripting.JavaScript.ThreadWorker.Run()

Function: void g::Fuse::AppBase::OnUnhandledException(::g::Uno::Exception *, bool)
Line: 748

ERROR: Native run failed. (pass --trace for stack trace)
```
From some simple debugging this looks like an off by one bug

**Comment by nekronos** [comment]
Steps to reproduce:
1. Build: [Archive.zip](https://github.com/fusetools/fuselibs-public/files/1466962/Archive.zip)
2. Click a list item on the first page
3. Click go back
4. Click the same item
5. Goto 3 until crash occurs

**Comment by nekronos** [comment]
In the cases I observed the array length and index was always 1 and 1 respectively
