### ISSUE TITLE
Attempted to detach child that is not attached to us

### ISSUE THREAD

**Issue by mortoray** [fusetools/fuselibs-public#922]
In my [Dice app](https://github.com/mortoray/dice)  I can predictably get the below error with these steps:

1. Add New Set Twice (button at bottom)
2. Delete Second set (swipe left, press Dleete)
3. Delete another set

```
Error: Fuse.Scripting.ScriptException: Uncaught Error: Internal error: Attempted to detach child that is not attached to us
Name: Error: Internal error: Attempted to detach child that is not attached to us
File name: FuseJS/Internal/zone.js
Line number: 196
Script stack trace: Error: Internal error: Attempted to detach child that is not attached to us
    at removeAsParentFrom (FuseJS/Internal/Model.js:320:12)
    at removeRange (FuseJS/Internal/Model.js:441:5)
    at Object.meta.diff (FuseJS/Internal/Model.js:246:7)
    at update (FuseJS/Internal/Model.js:392:15)
    at Object.meta.diff (FuseJS/Internal/Model.js:266:6)
    at FuseJS/Internal/Model.js:212:11
    at ZoneDelegate.invokeTask (FuseJS/Internal/zone.js:425:31)
    at Zone.runTask (FuseJS/Internal/zone.js:192:47)
    at ZoneTask.invokeTask (FuseJS/Internal/zone.js:499:34)
    at ZoneTask.invoke (FuseJS/Internal/zone.js:488:48)
```

I'll see if I can find a smaller reproduction.

High priority because it's a common use-case involving only basic behavior.

**Comment by mortoray** [comment]
Easier reproduction below. It appears you need to both and and remove from the list.

```
<App Model="MyModel">
	<StackPanel ItemSpacing="10">
		<Each Items="{items}">
			<Panel Height="50" Color="#AAA" Clicked="{deleteItem}">
				<Text Value="#{id}"/>
			</Panel>
		</Each>
		<Panel Height="50" Color="#AFA" Clicked="{addItem}">
			<Text Value="Add"/>
		</Panel>
	</StackPanel>
</App>
```

```
var ItemCount = 0
class Item {
	
	constructor() {
		this.id = ItemCount++
	}
}

export default class MyModel {
	constructor() {
		this.items = [ new Item(), new Item() ]
	}
	
	deleteItem( args ) {
		var ndx = this.items.indexOf(args.data)
		this.items.splice(ndx,1)
	}
	
	addItem( args ) {
		this.items.push( new Item() )
	}
}
```

**Comment by mortoray** [comment]
@sebbert I think this one is fairly critical to fix. I'm unable to create any app that deletes items from a list.

**Comment by sebbert** [comment]
@mortoray Can you verify if this fixes the issue? https://github.com/fusetools/fuselibs-public/pull/982
